### ISSUE TITLE
Zombie Process "npm run sass:bu"

### ISSUE THREAD

**Issue by Kirk1984** [PussTheCat-org/docker-quetre-quay#3]
Hello!

The Testsystem:
Raspberry Pi4
Ubuntu 22.04 Server
Docker rootless

Whenever i start the quetre Container it creates a Zombie process (npm run sass:bu). I found it via " ps aux | grep 'Z' ".

The container runs fine otherwise.

**Comment by zyachel** [comment]
@Kirk1984, it was probably due to the start command in `package.json`.  
I've fixed it since then.
